export const styleTips = [
    "Pair your traditional Punjabi with a contrasting waistcoat for a sophisticated festive look.",
    "For weddings, choose silk sarees with intricate gold zari work to stand out.",
    "Tailored fit is key; even the most exquisite embroidery won't shine if the fit is off.",
    "Accessorize your designer blouse with heavy jhumkas and a sleek bun.",
    "A hand-stitched Punjabi looks best when paired with traditional Kolhapuri chappals.",
    "Opt for pastel shades for daytime ceremonies and deep jewel tones for evening events.",
    "Let your heavy embroidery be the star by keeping your jewelry minimal.",
    "Traditional needlework on the cuffs and collar adds a subtle touch of elegance.",
    "Drape your saree in the classic seedha pallu style for a timeless appeal.",
    "A well-fitted designer blouse can transform a simple saree into a statement outfit.",
    "Velvet Punjabis are perfect for winter weddings, offering both warmth and royalty.",
    "Hand-done Kantha stitch work adds a unique, artisanal touch to your wardrobe.",
    "Balance a heavily embroidered dupatta with a solid-colored kurta or Punjabi.",
    "For a modern twist, wear your saree with a belt to accentuate your waist.",
    "Classic white Punjabis with Chikankari work are a must-have for every traditional wardrobe.",
    "Experiment with high-neck blouses to add a contemporary feel to your ethnic look.",
    "The right footwear can elevate your traditional attire; consider mojaris or juttis.",
    "Ensure your saree's length is perfect—it should graze the floor for an elegant silhouette.",
    "Floral embroidery is perfect for spring celebrations and outdoor events.",
    "Use a safety pin on the inside of your pleats to keep your saree drape secure all day.",
    "A contrast-colored pocket square can add a pop of color to your formal Punjabi.",
    "Kosa silk is known for its rich texture; let the fabric speak for itself.",
    "For a regal look, choose blouses with elbow-length sleeves and heavy border work.",
    "Traditional necklines like 'Paan' or 'Sweetheart' never go out of style.",
    "Preserve your handcrafted pieces by storing them in breathable cotton bags.",
    "A neatly folded pocket watch can add a vintage charm to your ethnic ensemble.",
    "Match your bindi with the most prominent color of your saree's embroidery.",
    "Layering a thin chain over a high-neck Punjabi adds a touch of modern luxury.",
    "Zardosi work is ideal for grand occasions; choose it for maximum impact.",
    "The drape of your Punjabi depends on the quality of the fabric; choose premium cotton or silk.",
    "Traditional patterns like 'Butti' or 'Paisley' are infinitely versatile.",
    "A subtle shimmer in your saree fabric catch the light beautifully during evening events.",
    "For a minimalist look, choose tone-on-tone embroidery on your Punjabi.",
    "Backless or deep-back blouses add a bold element to your traditional attire.",
    "Always dry-clean your heavily embroidered pieces to maintain their intricate work.",
    "A hand-stitched border on a plain saree adds a touch of bespoke luxury.",
    "Choose breathable fabrics like linen or cotton for summer festive wear.",
    "Traditional motifs inspired by nature are always in vogue.",
    "The color of your Punjabi should complement your skin tone; try warmer hues for evening wear.",
    "A perfectly pleated saree shows off the craftsmanship of the border work.",
    "Intricate needlework on the back of the blouse is a great way to surprise with detail.",
    "Classic silver jewelry pairs beautifully with cotton and handloom sarees.",
    "A traditional stole or dupatta can add layers of texture to a basic Punjabi.",
    "Focus on the neckline embroidery—it's the first thing people notice.",
    "Traditional attire is about comfort as much as style; ensure you can move freely.",
    "Darker shades like maroon, navy, and emerald green are perfect for reception nights.",
    "A gold-toned border is a classic that pairs well with almost any color.",
    "Embroidered buttons on a Punjabi are a small detail that makes a big difference.",
    "Your traditional look is complete with a confident smile—wear it with pride!",
    "Trust the artisans; the imperfections in hand-stitched work are what make it authentic."
];
